spring:
  application:
    name: boot-example-high-volume-traffic
  cache:
    type: simple
    cache-names:        # This 'cache-names' can limit the name spaces for Cache. If this property doesn't exist, it will allow all. If exist, only the listed names will be allowed to cache
    - cached-single

server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    max-connections: 20000
    threads:
      max: 1000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
